In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.__version__ #pandas version


'2.1.4'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv') 
#read data in pandas

In [5]:
df.head() #review of data

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
df.info() #count of data record as well as columns with missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [7]:
df['fuel_type'].unique() #fuel types

array(['Gasoline', 'Diesel'], dtype=object)

In [8]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [9]:
df_asia =df[df['origin'] == 'Asia']

df_asia #asia subset

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [10]:
df_asia['fuel_efficiency_mpg'].max() #fuel efficiency for asia

23.759122836520497

In [11]:
df['horsepower'].median() #initial median for horsepower

149.0

In [12]:
df['horsepower'].value_counts().max() #most reoccuring horsepower

142

In [13]:
df2 = df.fillna(df['horsepower'].value_counts().max())

In [14]:
df2['horsepower'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 9704 entries, 0 to 9703
Series name: horsepower
Non-Null Count  Dtype  
--------------  -----  
9704 non-null   float64
dtypes: float64(1)
memory usage: 75.9 KB


In [15]:
df2['horsepower'].median() #final median for horsepower

146.0

In [16]:
df_asia2 = df_asia[['vehicle_weight','model_year']]

In [17]:
df_asia2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3247 entries, 8 to 9703
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   vehicle_weight  3247 non-null   float64
 1   model_year      3247 non-null   int64  
dtypes: float64(1), int64(1)
memory usage: 76.1 KB


In [18]:
df_asia3 = df_asia2.head(7)

In [19]:
df_asia3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 8 to 38
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   vehicle_weight  7 non-null      float64
 1   model_year      7 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 168.0 bytes


In [20]:
x= np.array(df_asia3)

In [21]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [22]:
xTx = x@x.T

In [23]:
xTx

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [24]:
xTx_i = np.linalg.inv(xTx) #inverse of xTx

In [25]:
xTx_i

array([[ 6.27784782e+08,  4.52348582e+08, -5.52589667e+08,
        -5.04518657e+08, -1.36497506e+08, -9.70745174e+07,
         2.07769569e+08],
       [ 6.52427761e+08,  1.18496810e+09, -8.15933475e+08,
        -7.54720098e+08, -7.08834488e+08,  2.53306835e+08,
         1.86771033e+08],
       [-4.82034184e+08, -5.85397198e+08,  3.79915957e+08,
         6.66310906e+08,  1.18051009e+08, -1.47095872e+08,
         5.16329750e+07],
       [-4.86725764e+08, -5.86851309e+08,  7.06448581e+08,
         6.82137781e+08,  2.06347119e+08, -3.29606193e+08,
        -1.88697388e+08],
       [-2.37576087e+08, -7.37561522e+08,  2.26902495e+08,
         2.89910408e+08,  1.50145296e+08,  3.48995157e+08,
        -4.08718420e+07],
       [-2.28618838e+08,  1.97697960e+08, -2.05812130e+07,
        -2.25519129e+08,  3.60824331e+08, -2.92220029e+06,
        -8.08263491e+07],
       [ 1.52870693e+08,  7.43387198e+07,  7.67225188e+07,
        -1.51179749e+08,  9.23761238e+06, -2.62872552e+07,
        -1.3533841

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [27]:
xT = x.T
XT_max = xT @ xTx_i

In [28]:
w = XT_max @ y

In [29]:
w

array([ 1.10015869, -0.09307861])

In [30]:
w.sum()

1.007080078125

NameError: name 'homework1_mlzoomcamp' is not defined